using Godot;

/// <summary>
/// Visual overlay for a room card: banner header + icon + description + divider +
/// footer, matching the room-card treatment in ui_overhaul.png. Frame chrome (border/
/// banner/divider/footer) is built entirely from native Control/Panel/Label/ColorRect
/// nodes, per the coordinator's steer that new UI CHROME for this redesign should come
/// from StyleBoxFlat/ColorRect primitives rather than new image assets. The icon/
/// illustration area is the one exception (chunk 6): Monster/Weapon/Potion cards show
/// the REAL picture from card_assets/art/{name}.svg (a background-free illustration-
/// only SVG generated by tools/gen_cards.py's make_card_art_only) rather than invented
/// line art, since the user corrected chunk 2's hand-drawn RoomCardIcon after seeing it
/// next to the existing (much richer) card art. Friendly cards (Blacksmith/Merchant/
/// PotionJoker/WeaponJoker) have no real art yet and keep the hand-drawn icon.
///
/// Added as a plain child Control directly on the addon's Card GodotObject — the same
/// technique ScoundrelGame's AddSlainBadge/RemoveSlainBadges/ClearSlainBadges already
/// use to put weapon slain-monster badges on top of a Card without touching
/// addons/card-framework/ (see ScoundrelGame.cs ~1143, "AddSlainBadge"). Added as the
/// last child so it paints over the addon's own front_image art (the generic per-suit
/// SVG), with MouseFilter Ignore throughout so clicks/drags still reach the Card
/// control beneath for the existing drag-drop machinery.
///
/// Built once per card — banner color/name/icon/footer never change, since a card's
/// Suit/Rank are fixed for its lifetime — and reused for as long as that card stays in
/// the room. Only UpdateDescription is called again on every
/// ScoundrelGame.SyncRoomCardOverlays() tick, since the tooltip text it mirrors
/// depends on live state (equipped weapon, weapon floor, potion-used flag, health,
/// attack bonuses).
/// </summary>
public partial class RoomCardOverlay : Control
{
    public const string GroupName = "room_card_overlay";

    private const int   CornerRadius    = 10;
    private const float Padding         = 14f;
    private const float BannerHeight    = 46f;
    private const float IconHeight      = 170f;
    private const float FooterHeight    = 28f;
    private const float FooterBottomGap = 12f;
    private const float DividerGap      = 10f;
    private const float DescGap         = 8f;

    private Label _descriptionLabel = null!;

    public static RoomCardOverlay Create(CardModel card, Vector2 cardSize)
    {
        var overlay = new RoomCardOverlay
        {
            Name        = "RoomCardOverlay",
            Position    = Vector2.Zero,
            Size        = cardSize,
            MouseFilter = MouseFilterEnum.Ignore,
            // The addon bumps a card's z_index by CardFrameworkSettings.VISUAL_DRAG_Z_OFFSET
            // (1000) while HOVERING/HOLDING/MOVING (draggable_object.gd) and Pile-derived
            // containers separately force VISUAL_PILE_Z_INDEX+i (3000+i, pile.gd) as the
            // resting z_index -- a low value here (this was ZIndex=1) gets outrun by either,
            // revealing the addon's raw card art on hover/drag. 4090 clears every combination
            // of both with margin, while staying under Godot's z_index range limit.
            ZIndex      = 4090,
        };
        overlay.AddToGroup(GroupName);
        overlay.Build(card, cardSize);
        return overlay;
    }

    /// <summary>Refreshes the state-dependent description body text in place.</summary>
    public void UpdateDescription(string text) => _descriptionLabel.Text = text;

    private void Build(CardModel card, Vector2 cardSize)
    {
        float w = cardSize.X, h = cardSize.Y;
        var family = RoomCardContent.BannerFamily(card.Kind);
        var (bannerBg, bannerFg) = BannerColors(card, family);

        // Opaque background + thin border, covering the addon's generic front_image
        // art beneath (a StyleBoxFlat panel, not a background image/9-patch).
        var backgroundStyle = new StyleBoxFlat { BgColor = ScoundrelPalette.CardBackMaroon, BorderColor = ScoundrelPalette.DividerGoldBrown };
        backgroundStyle.SetBorderWidthAll(2);
        backgroundStyle.SetCornerRadiusAll(CornerRadius);
        var background = new Panel { OffsetRight = w, OffsetBottom = h, MouseFilter = MouseFilterEnum.Ignore };
        background.AddThemeStyleboxOverride("panel", backgroundStyle);
        AddChild(background);

        // Banner header bar — a top-to-bottom gradient (per direct feedback: "card
        // banners ... have gradients instead of solid colors") via StyleBoxTexture +
        // GradientTexture2D, the idiomatic native Godot combo for a gradient fill
        // (StyleBoxFlat's bg_color is flat-only). Confirmed via local screenshot:
        // StyleBoxTexture has no corner-radius equivalent, so its own corners come
        // out square, regressing the "rounded card corners" fix. Patched with two
        // small corner masks below rather than reverting to a flat fill.
        var banner = new Panel { OffsetRight = w, OffsetBottom = BannerHeight, MouseFilter = MouseFilterEnum.Ignore };
        banner.AddThemeStyleboxOverride("panel", BannerGradient.Style(bannerBg));
        AddChild(banner);
        AddChild(BannerGradient.CornerMask(w, CornerRadius, isLeft: true));
        AddChild(BannerGradient.CornerMask(w, CornerRadius, isLeft: false));

        var bannerLabel = new Label
        {
            Text                = RoomCardContent.DisplayName(card),
            OffsetLeft          = Padding * 0.5f,
            OffsetRight         = w - Padding * 0.5f,
            OffsetBottom        = BannerHeight,
            HorizontalAlignment = HorizontalAlignment.Center,
            VerticalAlignment   = VerticalAlignment.Center,
            AutowrapMode        = TextServer.AutowrapMode.Word,
            ClipText            = true,
            MouseFilter         = MouseFilterEnum.Ignore,
        };
        bannerLabel.AddThemeFontOverride("font", ScoundrelPalette.DisplayBold);
        bannerLabel.AddThemeFontSizeOverride("font_size", 17);
        bannerLabel.AddThemeColorOverride("font_color", bannerFg);
        AddChild(bannerLabel);

        // Icon area. Monster/Weapon/Potion cards have real thematic art: a second,
        // separately-generated SVG under card_assets/art/{name}.svg containing ONLY
        // the illustration (same generator, tools/gen_cards.py's make_card_art_only,
        // skips the background/hatch/border/corner-marks/rank-text/name-banner that
        // the regular card_assets/*.svg draws around it) — loaded directly, no
        // runtime cropping needed since the art file already contains just the
        // picture. Friendly cards (Blacksmith/Merchant/PotionJoker/WeaponJoker) have
        // no real art yet, so they keep chunk 2's hand-drawn RoomCardIcon.
        Control icon = family == RoomCardBannerFamily.Friendly
            ? new RoomCardIcon
            {
                Kind         = card.Kind,
                LineColor    = FriendlyIconColor(card.Kind),
                OffsetTop    = BannerHeight,
                OffsetRight  = w,
                OffsetBottom = BannerHeight + IconHeight,
                MouseFilter  = MouseFilterEnum.Ignore,
            }
            : new TextureRect
            {
                Texture      = GD.Load<Texture2D>($"res://card_assets/art/{card.Name}.svg"),
                StretchMode  = TextureRect.StretchModeEnum.KeepAspectCentered,
                OffsetTop    = BannerHeight,
                OffsetRight  = w,
                OffsetBottom = BannerHeight + IconHeight,
                MouseFilter  = MouseFilterEnum.Ignore,
            };
        AddChild(icon);

        // Footer/divider geometry, computed first so the description area fills
        // whatever space remains above it.
        float footerY    = h - FooterHeight - FooterBottomGap;
        float dividerY   = footerY - DividerGap;
        float descTop    = BannerHeight + IconHeight + DescGap;
        float descBottom = dividerY - DescGap;

        _descriptionLabel = new Label
        {
            OffsetLeft        = Padding,
            OffsetTop         = descTop,
            OffsetRight       = w - Padding,
            OffsetBottom      = descBottom,
            AutowrapMode      = TextServer.AutowrapMode.Word,
            VerticalAlignment = VerticalAlignment.Top,
            MouseFilter       = MouseFilterEnum.Ignore,
        };
        _descriptionLabel.AddThemeFontOverride("font", ScoundrelPalette.SerifRegular);
        _descriptionLabel.AddThemeFontSizeOverride("font_size", 11);
        _descriptionLabel.AddThemeColorOverride("font_color", ScoundrelPalette.DescriptionGray);
        AddChild(_descriptionLabel);

        // Divider — a plain thin ColorRect, not an image.
        var divider = new ColorRect
        {
            Color        = ScoundrelPalette.DividerGoldBrown,
            OffsetLeft   = Padding,
            OffsetTop    = dividerY,
            OffsetRight  = w - Padding,
            OffsetBottom = dividerY + 1f,
            MouseFilter  = MouseFilterEnum.Ignore,
        };
        AddChild(divider);

        // Footer row: suit glyph + value for monster/weapon/potion, or a role tag +
        // sparkle for the friendly kinds (Blacksmith/Merchant/PotionJoker/WeaponJoker).
        int? footerValue = RoomCardContent.FooterValue(card);
        bool isFriendly  = family == RoomCardBannerFamily.Friendly;

        var footerLeft = new Label
        {
            Text              = RoomCardContent.FooterLeftText(card),
            OffsetLeft        = Padding,
            OffsetTop         = footerY,
            OffsetRight       = w * 0.6f,
            OffsetBottom      = footerY + FooterHeight,
            VerticalAlignment = VerticalAlignment.Center,
            MouseFilter       = MouseFilterEnum.Ignore,
        };
        footerLeft.AddThemeFontOverride("font", ScoundrelPalette.SerifRegular);
        footerLeft.AddThemeFontSizeOverride("font_size", 13);
        footerLeft.AddThemeColorOverride("font_color", isFriendly ? ScoundrelPalette.BrightGold : ScoundrelPalette.MutedGoldGray);
        AddChild(footerLeft);

        var footerRight = new Label
        {
            Text                = footerValue.HasValue ? footerValue.Value.ToString() : "✦", // sparkle glyph
            OffsetLeft          = w * 0.6f,
            OffsetTop           = footerY,
            OffsetRight         = w - Padding,
            OffsetBottom        = footerY + FooterHeight,
            HorizontalAlignment = HorizontalAlignment.Right,
            VerticalAlignment   = VerticalAlignment.Center,
            MouseFilter         = MouseFilterEnum.Ignore,
        };
        footerRight.AddThemeFontOverride("font", ScoundrelPalette.DisplayBold);
        footerRight.AddThemeFontSizeOverride("font_size", footerValue.HasValue ? 24 : 18);
        // Monster damage reads in a brighter red than the monster banner itself (for
        // contrast against the dark card background); every other footer value/sparkle
        // uses the same bright gold as the rest of the UI's numeric readouts.
        footerRight.AddThemeColorOverride("font_color", card.Kind == CardKind.Monster ? ScoundrelPalette.MonsterRedValue : ScoundrelPalette.BrightGold);
        AddChild(footerRight);
    }

    // Jokers keep their own companion identity color (red/near-black, same as
    // CompanionPanelOverlay uses once they're taken) even as an anonymous room card,
    // rather than the shared Blacksmith/Merchant "friendly NPC" gold-orange -- a
    // Joker looking different in the room than once equipped read as wrong (the user
    // flagged this directly). Blacksmith/Merchant still share one NPC color, now
    // tuned further from Weapon's gold so the two don't read as the same hue.
    // Potion uses the same pink as the "Potions" REMAINING-tally text
    // (ScoundrelPalette.PotionRoseBright) instead of a red that matched nothing else
    // on screen -- paired with dark (not white) banner text, mirroring how the NPC
    // gold-orange banner already pairs a light fill with dark text.
    // RoomCardIcon's hand-drawn line art needs a BRIGHT color to read against the
    // near-black card background — the actual banner fills (CompanionRedBanner/
    // CompanionBlackBanner, BannerGoldFriendly) are tuned to host white/dark banner
    // text and are mostly too dark or too similar to the background for line art.
    // Same accents CompanionPanelOverlay already uses for these exact two Joker
    // kinds, reused here rather than inventing near-duplicate colors.
    private static Color FriendlyIconColor(CardKind kind) => kind switch
    {
        CardKind.PotionJoker => ScoundrelPalette.MonsterRedValue,
        CardKind.WeaponJoker => ScoundrelPalette.BrightGold,
        _                    => ScoundrelPalette.BannerGoldFriendly, // Blacksmith/Merchant
    };

    private static (Color bg, Color fg) BannerColors(CardModel card, RoomCardBannerFamily family)
    {
        if (card.Kind == CardKind.PotionJoker) return (ScoundrelPalette.CompanionRedBanner, Colors.White);
        if (card.Kind == CardKind.WeaponJoker) return (ScoundrelPalette.CompanionBlackBanner, Colors.White);
        if (family == RoomCardBannerFamily.Friendly)
            return (ScoundrelPalette.BannerGoldFriendly, ScoundrelPalette.BackgroundNearBlack);

        return card.Suit switch
        {
            Suit.Clubs    => (ScoundrelPalette.BannerClubsGreen, Colors.White),
            Suit.Spades   => (ScoundrelPalette.BannerSpadesPurple, Colors.White),
            Suit.Diamonds => (ScoundrelPalette.BannerDiamondsGold, Colors.White),
            Suit.Hearts   => (ScoundrelPalette.PotionRoseBright, ScoundrelPalette.BackgroundNearBlack),
            _ => throw new System.InvalidOperationException($"Suit {card.Suit} has no room-card banner color."),
        };
    }
}
